name: Test and deploy Android

on:
  push:

jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: MarekMaslanka/remocy-client
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Unit tests
        run: |
          chmod +x gradlew
          ./gradlew test

  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: MarekMaslanka/remocy-client
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

  android_tests:
    runs-on: [ macos-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: MarekMaslanka/remocy-client
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
